// Generated by scripts/export_task_contract.py. Do not edit.

export type SourceState = 'open' | 'done' | 'unknown';

export type SourceAvailability = 'present' | 'missing' | 'unconfirmed';

export type FieldAvailability = 'known' | 'empty' | 'unread' | 'unknown';

export type TaskField =
  | 'due_at'
  | 'available_at'
  | 'closes_at'
  | 'description'
  | 'submission_status'
  | 'score'
  | 'graded'
  | 'points_possible';
