"""Run with Python from any directory; --check never modifies files."""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from coursedeck.task_state import contract  # noqa: E402


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    values = contract()
    types = "// Generated by scripts/export_task_contract.py. Do not edit.\n\n"
    for name, key in (
        ("SourceState", "source_states"),
        ("SourceAvailability", "source_availability"),
        ("FieldAvailability", "field_availability"),
        ("TaskField", "fields"),
    ):
        members = [f"'{value}'" for value in values[key]]
        line = f"export type {name} = " + " | ".join(members) + ";"
        types += (
            line
            if len(line) <= 100
            else f"export type {name} =\n" + "\n".join(f"  | {item}" for item in members) + ";"
        ) + "\n\n"
    artifacts = {
        "task-contract.json": json.dumps(values, indent=2, ensure_ascii=False) + "\n",
        "task-contract-types.ts": types.rstrip() + "\n",
    }
    for filename, output in artifacts.items():
        destination = ROOT / "frontend/src" / filename
        if args.check:
            if not destination.exists() or destination.read_text(encoding="utf-8") != output:
                parser.exit(1, f"{filename} is stale; run python scripts/export_task_contract.py\n")
        else:
            destination.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
