"""Decode assignment timing from responses generated by the Classroom page itself.

This is an observed, undocumented schema, not a separately replayed Google API.
Accept only a record with a matching course, assignment ID, type and title.
Never persist the response envelope (it can contain unrelated private fields).
"""

import json
from datetime import UTC, datetime


def assignment_timing(body: str, course_id: str, assignment_id: str, title: str) -> dict | None:
    def visit(value, depth=0):
        if depth > 30 or not isinstance(value, list):
            return None
        # Classroom's wrb.fr wrapper carries the inner JSON as a string.
        if len(value) >= 3 and value[0] == "wrb.fr" and isinstance(value[2], str):
            try:
                return visit(json.loads(value[2]), depth + 1)
            except ValueError:
                return None
        try:
            if len(value) >= 2 and value[0] == 2 and isinstance(value[1], list):
                header, timing = value[1][:2]
                if (
                    isinstance(header, list)
                    and len(header) > 10
                    and header[0] == [assignment_id, [course_id]]
                    and isinstance(header[5], str)
                    and header[5].strip() == title.strip()
                    and header[8] == 2
                    and isinstance(timing, list)
                    and len(timing) >= 3
                ):
                    stamp = timing[0]
                    # A missing timestamp is not assumed to mean "no deadline".
                    if type(stamp) is int and 631152000000 <= stamp < 7258118400000:
                        return {
                            "due_at": datetime.fromtimestamp(stamp / 1000, UTC),
                            "source_updated_at": datetime.fromtimestamp(header[2] / 1000, UTC)
                            if type(header[2]) is int and 631152000000 <= header[2] < 7258118400000
                            else None,
                        }
        except (ValueError, TypeError, IndexError, OverflowError):
            pass
        for child in value:
            found = visit(child, depth + 1)
            if found:
                return found
        return None

    if len(body) > 4_000_000:
        return None
    for line in body.splitlines():
        if not line.startswith("["):
            continue
        try:
            found = visit(json.loads(line))
            if found:
                return found
        except ValueError:
            pass
    return None
